#!/usr/bin/env python3
"""One-shot prod deploy for plenty-mirakl-connector.

Mirror of .deploy_staging.py but targets /opt/plenty-mirakl-prod, project
plenty-mirakl-prod, compose docker-compose.prod.yml, env file .env, and
domain connector.vagabond-consulting.com. Uses prod secrets from
~/.claude/credentials/plenty-mirakl-prod.env.
"""
from __future__ import annotations
import os
import sys
import time
from pathlib import Path

import paramiko


def load_env(path: str) -> dict:
    p = Path(path).expanduser()
    env: dict[str, str] = {}
    if p.is_file():
        for line in p.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            env.setdefault(k.strip(), v.strip())
    return env


SBOX = load_env("~/.claude/credentials/servicebox.env")
SECRETS = load_env("~/.claude/credentials/plenty-mirakl-prod.env")
PLENTY = load_env("~/.claude/credentials/plenty-test-p73736.env")
MIRAKL = load_env("~/.claude/credentials/mirakl-douglas2-dev.env")

HOST = SBOX["SERVER_IP"]
USER = SBOX["SSH_USER"]
PASS = SBOX["SSH_PASS"]
PORT = int(SBOX.get("SSH_PORT", "22"))

REMOTE_DIR = "/opt/plenty-mirakl-prod"
COMPOSE_FILE = "docker-compose.prod.yml"
PROJECT = "plenty-mirakl-prod"
DOMAIN = "connector.vagabond-consulting.com"
ENV_FILE = ".env"  # prod compose reads .env (not .env.staging)

LOCAL = Path(__file__).parent.resolve()


def connect() -> paramiko.SSHClient:
    cli = paramiko.SSHClient()
    cli.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    cli.connect(HOST, port=PORT, username=USER, password=PASS,
                look_for_keys=False, allow_agent=False, timeout=30)
    return cli


def run(cli, cmd, sudo=False, quiet=False, timeout=300):
    if sudo:
        full = f"echo {PASS!r} | sudo -S -p '' bash -c {cmd!r}"
    else:
        full = cmd
    if not quiet:
        print(f"$ {cmd[:160]}{'...' if len(cmd) > 160 else ''}")
    chan = cli.get_transport().open_session()
    chan.set_combine_stderr(True)
    chan.settimeout(timeout)
    chan.exec_command(full)
    chunks = []
    deadline = time.time() + timeout
    while True:
        if chan.recv_ready():
            c = chan.recv(8192)
            if c:
                chunks.append(c.decode(errors="replace"))
        if chan.exit_status_ready() and not chan.recv_ready():
            break
        if time.time() > deadline:
            break
        time.sleep(0.1)
    while chan.recv_ready():
        chunks.append(chan.recv(8192).decode(errors="replace"))
    out = "".join(chunks)
    rc = chan.recv_exit_status()
    if not quiet:
        try:
            print(out.rstrip()[-2000:])
        except UnicodeEncodeError:
            print(out.rstrip()[-2000:].encode("ascii", "replace").decode())
    return out, rc


def upload_dir(sftp, local: Path, remote: str):
    skip_dirs = {".git", ".venv", ".venv-deploy", "venv", "__pycache__", "node_modules",
                 ".idea", ".vscode", "data", "logs", ".pytest_cache", "htmlcov", "dist", "build"}
    skip_files_prefix = {".env"}
    skip_files_exact = {".DS_Store"}
    allowed_dotfiles = {".gitignore", ".env.example"}

    try:
        sftp.stat(remote)
    except IOError:
        sftp.mkdir(remote)

    for entry in sorted(local.rglob("*")):
        rel = entry.relative_to(local)
        parts = rel.parts
        if any(p in skip_dirs for p in parts):
            continue
        if entry.name.startswith(".") and entry.name not in allowed_dotfiles:
            if any(entry.name.startswith(pfx) for pfx in skip_files_prefix):
                continue
            if entry.is_file() and entry.name not in allowed_dotfiles:
                continue
        if entry.name in skip_files_exact:
            continue
        rpath = f"{remote}/{rel.as_posix()}"
        if entry.is_dir():
            try:
                sftp.mkdir(rpath)
            except IOError:
                pass
        else:
            sftp.put(str(entry), rpath)


def build_env_text() -> str:
    lines = [
        "# AUTO-GENERATED by .deploy_prod.py — do not edit on server",
        "ENV=prod",
        "LOG_LEVEL=INFO",
        f"BASE_URL=https://{DOMAIN}",
        f"TRAEFIK_DOMAIN={DOMAIN}",
        "",
        "# --- Database ---",
        f"POSTGRES_PASSWORD={SECRETS['POSTGRES_PASSWORD']}",
        f"DATABASE_URL=postgresql+asyncpg://connector:{SECRETS['POSTGRES_PASSWORD']}@postgres:5432/connector",
        "",
        "# --- Redis ---",
        "REDIS_URL=redis://redis:6379/0",
        "",
        "# --- App secrets (PROD) ---",
        f"FERNET_KEY={SECRETS['FERNET_KEY']}",
        f"ADMIN_API_KEY={SECRETS['ADMIN_API_KEY']}",
        f"SESSION_SECRET={SECRETS['SESSION_SECRET']}",
        "",
        "# --- Stripe (TEST mode — live keys not yet authorized) ---",
        f"STRIPE_SECRET_KEY={SECRETS['STRIPE_SECRET_KEY']}",
        f"STRIPE_WEBHOOK_SECRET={SECRETS['STRIPE_WEBHOOK_SECRET']}",
        f"STRIPE_PRICE_DEFAULT={SECRETS['STRIPE_PRICE_DEFAULT']}",
        f"STRIPE_PRICE_OVERAGE={SECRETS['STRIPE_PRICE_OVERAGE']}",
        "",
        "# --- Plenty test sandbox (legacy single-tenant seed; multi-tenant overrides via DB) ---",
        f"PLENTY_BASE_URL={PLENTY['PLENTY_BASE_URL']}",
        f"PLENTY_USERNAME={PLENTY['PLENTY_USERNAME']}",
        f"PLENTY_PASSWORD={PLENTY['PLENTY_PASSWORD']}",
        "PLENTY_REFERRER_ID=1",
        "PLENTY_WAREHOUSE_ID=1",
        "PLENTY_PLENTY_ID=0",
        "",
        "# --- Mirakl Douglas dev sandbox ---",
        f"MIRAKL_BASE_URL={MIRAKL['MIRAKL_BASE_URL']}",
        f"MIRAKL_API_KEY={MIRAKL['MIRAKL_API_KEY']}",
        f"MIRAKL_SHOP_ID={MIRAKL['MIRAKL_SHOP_ID']}",
        "",
        "# --- Ops ---",
        "OPS_EMAIL=romic@vagabond-consulting.com",
        "DRY_RUN=false",
    ]
    return "\n".join(lines) + "\n"


def main():
    print(f"[deploy-prod] target {USER}@{HOST}:{REMOTE_DIR}")
    cli = connect()

    bundle = " && ".join([
        "docker compose version | head -1",
        "docker network ls | grep -q traefik_default || (echo MISSING_NETWORK; exit 1)",
        f"mkdir -p {REMOTE_DIR}",
        "echo PREP_OK",
    ])
    out, rc = run(cli, bundle, quiet=False, timeout=60)
    if "PREP_OK" not in out:
        print("Prep failed!")
        cli.close()
        sys.exit(1)

    out, _ = run(cli, "docker ps --format '{{.Names}}'", quiet=True)
    before = set(out.split())
    print(f"[snapshot] {len(before)} containers running before deploy")

    print(f"[upload] {LOCAL} -> {REMOTE_DIR}")
    sftp = cli.open_sftp()
    upload_dir(sftp, LOCAL, REMOTE_DIR)

    env_text = build_env_text()
    with sftp.file(f"{REMOTE_DIR}/{ENV_FILE}", "w") as f:
        f.write(env_text)
    sftp.chmod(f"{REMOTE_DIR}/{ENV_FILE}", 0o600)
    print(f"[env] wrote {ENV_FILE} ({len(env_text.splitlines())} lines, chmod 600)")
    sftp.close()

    dc = f"docker compose -p {PROJECT} --env-file {ENV_FILE} -f {COMPOSE_FILE}"
    out, rc = run(cli, f"cd {REMOTE_DIR} && {dc} build 2>&1 | tail -50", timeout=600)
    if rc != 0:
        print(f"BUILD FAILED rc={rc}")
        cli.close()
        sys.exit(2)

    out, rc = run(cli, f"cd {REMOTE_DIR} && {dc} up -d 2>&1", timeout=180)
    if rc != 0:
        print(f"UP FAILED rc={rc}")
        cli.close()
        sys.exit(3)

    print("[health] waiting for api healthz...")
    for i in range(30):
        out, _ = run(cli, f"cd {REMOTE_DIR} && {dc} exec -T api curl -fsS http://localhost:8000/healthz 2>&1 || echo WAIT", quiet=True, timeout=15)
        if '"ok":true' in out or '"ok": true' in out:
            print(f"  internal healthz OK after {i*3}s")
            break
        time.sleep(3)
    else:
        print("  internal healthz did NOT come up in 90s — dumping logs")
        run(cli, f"cd {REMOTE_DIR} && {dc} logs api --tail=80")
        cli.close()
        sys.exit(4)

    out, _ = run(cli, f"cd {REMOTE_DIR} && {dc} exec -T api alembic current 2>&1", quiet=True, timeout=30)
    print(f"[alembic] current: {out.strip()[-300:]}")

    print("[health] external HTTPS healthz (allows up to 90s for cert)...")
    for i in range(30):
        out, _ = run(cli, f"curl -fsS -o /tmp/h.txt -w '%{{http_code}}' https://{DOMAIN}/healthz 2>&1 || echo FAIL",
                    quiet=True, timeout=15)
        if "200" in out:
            print(f"  external HTTPS /healthz 200 after {i*3}s")
            break
        time.sleep(3)
    else:
        print(f"  external HTTPS NOT reachable in 90s; last: {out.strip()}")

    out, _ = run(cli, "docker ps --format '{{.Names}}'", quiet=True)
    after = set(out.split())
    missing = before - after
    if missing:
        print(f"!!! WARN: containers MISSING after deploy: {sorted(missing)}")
    else:
        print(f"[verify] all {len(before)} pre-existing containers still running.")

    out, _ = run(cli, f"curl -fsS https://{DOMAIN}/ 2>&1 | head -c 400 || echo FAIL", quiet=True, timeout=10)
    landing_ok = "PlentyMirakl" in out or "plenty" in out.lower()
    print(f"[landing] reachable: {landing_ok}")
    print(out[:300])

    cli.close()
    print("\n[deploy-prod] DONE")
    return 0


if __name__ == "__main__":
    sys.exit(main())
