server {
  listen 80 default_server;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  # security + caching
  add_header X-Content-Type-Options "nosniff" always;
  add_header X-Frame-Options "SAMEORIGIN" always;
  add_header Referrer-Policy "strict-origin-when-cross-origin" always;
  add_header Permissions-Policy "geolocation=(), microphone=(), camera=()" always;

  location ~* \.(css|js|png|svg|ico)$ {
    expires 7d;
    add_header Cache-Control "public, max-age=604800, immutable";
  }

  location / {
    try_files $uri $uri.html $uri/ =404;
  }

  # health
  location = /healthz { return 200 "ok\n"; add_header Content-Type text/plain; }
}
